server:
  port: 8084  # ${PORT:8080}
profile: new_profile
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka.eureka--dev-space:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  sleuth:
    sampler:
      percentage: 1.0
