server:
  port: 8084
profile: profile
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 'http://eureka-eureka.diablo-auto-asf-auto-415:8761/eureka/'
  instance:
    preferIpAddress: true
    instance-id: '${spring.cloud.client.ipAddress}:${server.port}'
spring:
  sleuth:
    sampler:
      percentage: 1
